-- Duty scheduler schema (PostgreSQL / Neon). Tables are prefixed ds_.
CREATE TABLE IF NOT EXISTS ds_groups (id text PRIMARY KEY, name text NOT NULL, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ds_posts (id text PRIMARY KEY, name text NOT NULL, min_personnel int NOT NULL DEFAULT 1, max_personnel int, required_personnel int, required_per_slot int NOT NULL DEFAULT 1, is_24_hours boolean NOT NULL DEFAULT true, active boolean NOT NULL DEFAULT true, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ds_personnel (id text PRIMARY KEY, code text UNIQUE NOT NULL, name text NOT NULL, group_id text REFERENCES ds_groups(id) ON UPDATE CASCADE ON DELETE SET NULL, default_post_id text REFERENCES ds_posts(id) ON UPDATE CASCADE ON DELETE SET NULL, active boolean NOT NULL DEFAULT true, note text, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ds_shift_types (id text PRIMARY KEY, name text NOT NULL, short_name text NOT NULL, counts_as_duty boolean NOT NULL DEFAULT false, counts_as_rest boolean NOT NULL DEFAULT false, counts_as_withdrawal boolean NOT NULL DEFAULT false, sort_order int NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS ds_settings (key text PRIMARY KEY, value jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ds_scenarios (id serial PRIMARY KEY, name text NOT NULL, description text, config jsonb NOT NULL, last_result jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ds_time_slots (id serial PRIMARY KEY, scenario_id int NOT NULL REFERENCES ds_scenarios(id) ON DELETE CASCADE, slot_index int NOT NULL, start_clock time NOT NULL, end_clock time NOT NULL, duration_minutes int NOT NULL, UNIQUE (scenario_id, slot_index));
CREATE TABLE IF NOT EXISTS ds_schedules (id bigserial PRIMARY KEY, scenario_id int NOT NULL REFERENCES ds_scenarios(id) ON DELETE CASCADE, date date NOT NULL, day_index int NOT NULL, slot_index int NOT NULL, post_id text, personnel_id text, group_id text, shift_type_id text NOT NULL REFERENCES ds_shift_types(id), start_min bigint NOT NULL, end_min bigint NOT NULL, manual_override boolean NOT NULL DEFAULT false, override_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK (NOT manual_override OR override_reason IS NOT NULL));
CREATE INDEX IF NOT EXISTS ds_schedules_scn ON ds_schedules (scenario_id, day_index, slot_index);
CREATE INDEX IF NOT EXISTS ds_schedules_person ON ds_schedules (scenario_id, personnel_id);
CREATE TABLE IF NOT EXISTS ds_schedule_revisions (id bigserial PRIMARY KEY, scenario_id int NOT NULL REFERENCES ds_scenarios(id) ON DELETE CASCADE, revision int NOT NULL, snapshot jsonb NOT NULL, note text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (scenario_id, revision));
