-- Seed only when the DB is empty. Time slots / schedules are NOT inserted: they are generated by the engine from the scenario config.
INSERT INTO ds_shift_types (id,name,short_name,counts_as_duty,counts_as_rest,counts_as_withdrawal,sort_order) VALUES ('on-duty','เข้า','เข้า',true,false,false,0),('withdraw','ถอน','ถอน',false,false,true,1),('rest','พัก','พัก',false,true,false,2) ON CONFLICT DO NOTHING;
INSERT INTO ds_groups (id,name,sort_order) VALUES ('A','กลุ่ม A',0),('B','กลุ่ม B',1) ON CONFLICT DO NOTHING;
INSERT INTO ds_posts (id,name,sort_order) VALUES ('P1','จุด 1',0),('P2','จุด 2',1),('P3','จุด 3',2) ON CONFLICT DO NOTHING;
INSERT INTO ds_personnel (id,code,name,group_id,sort_order) SELECT g||lpad(i::text,3,'0'), g||lpad(i::text,3,'0'), g||lpad(i::text,3,'0'), g, i FROM unnest(ARRAY['A','B']) g, generate_series(1,6) i ON CONFLICT DO NOTHING;
INSERT INTO ds_scenarios (name,description,config)
SELECT v.name, v.description, jsonb_build_object('startDate', to_char(current_date,'YYYY-MM-DD'),'days',7,'startTime','17:00','slotDuration',4,'peoplePerPost',v.ppp,'dutyHours',v.duty,'withdrawalHours',4,'alternateDays',true,'rotationEnabled',true,'nightStart','22:00','nightEnd','06:00','minimumRestHours',8,'maximumDutyHoursPerDay',null,'maximumDutyHoursPerPeriod',null)
FROM (VALUES ('Scenario A','3 คน/จุด เวร 8 ชม.',3,8),('Scenario B','2 คน/จุด เวร 8 ชม.',2,8),('Scenario C','2 คน/จุด เวร 12 ชม. (ทดลอง)',2,12)) AS v(name,description,ppp,duty)
WHERE NOT EXISTS (SELECT 1 FROM ds_scenarios);
